import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Header />
      <body className={inter.className}>{children}</body>
      <div className="w-full md:h-[100px] h-16 fixed bottom-0">
        <nav>footer</nav>
      </div>
    </html>
  );
}
